"use client";
import {FormEvent,useMemo,useState} from "react";
import {Activity,ArrowRight,BookOpen,CheckCircle2,Database,ExternalLink,FileSearch,FlaskConical,Hash,RefreshCw,ShieldCheck,Wallet,X} from "lucide-react";
import {GenLayerTransactionPanel,type SubmitInput,type TrackedStatus} from "@genlayer/transaction-kit-react";
import {GENLAYER_NETWORK,getContractAddress} from "@/lib/genlayer/client";
import {useWallet} from "@/lib/genlayer/wallet";
import {useTransactionKit} from "@/lib/genlayer/kit";
import {isConfirmedSuccess,transactionFailureLabel} from "@/lib/genlayer/transactionStatus";
import {useClaim,useClaimCount,useRefreshTrialClaim} from "@/lib/hooks/useTrialClaim";
import {toast} from "sonner";

const short=(v?:string|null)=>v?`${v.slice(0,6)}…${v.slice(-4)}`:"Connect wallet";
const tone=(v?:string)=>v==="ALIGNED"?"good":v==="MISALIGNED"?"bad":v==="PARTIAL"?"warn":"neutral";
function Pill({value}:{value?:string}){return <span className={`pill ${tone(value)}`}><i/>{value||"NOT ASSESSED"}</span>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

export function TrialClaimApp(){
 const wallet=useWallet(),kit=useTransactionKit(wallet.address),address=getContractAddress(),refresh=useRefreshTrialClaim();
 const count=useClaimCount(); const [lookup,setLookup]=useState(1); const record=useClaim(lookup);
 const [flow,setFlow]=useState<"register"|"assess"|"revise"|null>(null);
 const [nct,setNct]=useState("NCT04280705"),[statement,setStatement]=useState("The trial's registered primary endpoint measured time to recovery through Day 29."),[context,setContext]=useState("Public research summary");
 const [assessId,setAssessId]=useState("1"),[assessRevision,setAssessRevision]=useState("1");
 const [reviseId,setReviseId]=useState("1"),[reviseRevision,setReviseRevision]=useState("1"),[revised,setRevised]=useState("The trial registered time to recovery through Day 29 as a primary outcome."),[revisedContext,setRevisedContext]=useState("Corrected public summary");
 const registerTx=useMemo<SubmitInput>(()=>({kind:"write",address:address as `0x${string}`,method:"register_claim",args:[nct.trim().toUpperCase(),statement.trim(),context.trim()]}),[address,nct,statement,context]);
 const assessTx=useMemo<SubmitInput>(()=>({kind:"write",address:address as `0x${string}`,method:"assess_claim",args:[Number(assessId),Number(assessRevision)]}),[address,assessId,assessRevision]);
 const reviseTx=useMemo<SubmitInput>(()=>({kind:"write",address:address as `0x${string}`,method:"revise_claim",args:[Number(reviseId),Number(reviseRevision),revised.trim(),revisedContext.trim()]}),[address,reviseId,reviseRevision,revised,revisedContext]);
 const submit=(e:FormEvent,next:typeof flow)=>{e.preventDefault();if(!address)return toast.error("Contract address is not configured");if(!wallet.isConnected)return toast.error("Connect your wallet first");if(!wallet.isOnCorrectNetwork)return toast.error("Switch to GenLayer Studio Next, chain 61997");if(!kit)return toast.error("Transaction Kit is not ready");setFlow(next)};
 const done=(label:string)=>(s:TrackedStatus)=>{if(!isConfirmedSuccess(s))return toast.error(transactionFailureLabel(s));toast.success(`${label} confirmed by consensus`);setFlow(null);refresh()};
 return <>
  <header><a className="brand" href="#top"><span className="logo"><img src="/trialclaim-logo.png" alt=""/></span><span><b>TrialClaim</b><small>Evidence-bound clinical claims</small></span></a><nav><a href="#method">Method</a><a href="#registry">Registry</a><a href="#limits">Boundaries</a></nav><button className="wallet" onClick={()=>wallet.isConnected?wallet.disconnectWallet():wallet.connectWallet()}><i className={wallet.isConnected?"on":""}/><Wallet/>{wallet.isLoading?"Checking":short(wallet.address)}</button></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><span className="kicker"><FlaskConical/> CONSENSUS REVIEW ON GENLAYER</span><h1>Clinical claims,<br/><em>bound to evidence.</em></h1><p>Compare public statements with the registered primary outcomes of a ClinicalTrials.gov study. Validators fetch the canonical record, bind the exact evidence snapshot, and preserve every assessment on-chain.</p><div className="actions"><a className="primary" href="#registry">Review a claim <ArrowRight/></a><a className="secondary" href="https://clinicaltrials.gov" target="_blank">Explore source <ExternalLink/></a></div></div><div className="hero-art"><img src="/trialclaim-logo.png" alt="TrialClaim medical record illustration"/><div className="orbit one">NCT ID</div><div className="orbit two">SHA-256</div><div className="orbit three">CONSENSUS</div></div></section>
   <section className="metrics"><div><Database/><span>Authority<b>ClinicalTrials.gov</b></span></div><div><ShieldCheck/><span>Network<b>Studio Next · 61997</b></span></div><div><BookOpen/><span>Registered claims<b>{count.isLoading?"Loading":count.isError?"Unavailable":String(count.data??0)}</b></span></div><div><Hash/><span>Evidence binding<b>Fetched-byte digest</b></span></div></section>
   <section id="method" className="section"><div className="section-title"><span>WHAT IT PROVES</span><h2>One narrow question.<br/>A durable public record.</h2><p>TrialClaim does not decide whether a treatment works. It decides whether a statement accurately represents the registered primary outcomes for one exact NCT study.</p></div><div className="steps">{[["01","Register","Commit an exact public statement, NCT identifier and publication context."],["02","Acquire","Validators construct a fixed, bounded ClinicalTrials.gov API request."],["03","Compare","Consensus judges endpoint, subject and time-frame alignment."],["04","Preserve","Every assessment and revised claim remains append-only and auditable."]].map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
   <section id="registry" className="section registry"><div className="section-title compact"><div><span>LIVE REGISTRY</span><h2>Register, assess, revise.</h2></div><code>{address?short(address):"Deploy contract to activate"}</code></div><div className="grid"><div className="stack">
    <article className="card featured"><div className="card-head"><h3><FileSearch/> Register public claim</h3><small>01</small></div>{flow==="register"&&kit?<Review kit={kit} tx={registerTx} done={done("Claim registration")} close={()=>setFlow(null)}/>:<form onSubmit={e=>submit(e,"register")}><Field label="ClinicalTrials.gov ID"><input value={nct} onChange={e=>setNct(e.target.value)} pattern="NCT[0-9]{8}" required/></Field><Field label="Publication context"><input value={context} onChange={e=>setContext(e.target.value)} minLength={3} maxLength={120} required/></Field><Field label="Exact public statement"><textarea value={statement} onChange={e=>setStatement(e.target.value)} minLength={20} maxLength={500} required/></Field><button>Review registration <ArrowRight/></button></form>}</article>
    <div className="twocol"><article className="card"><div className="card-head"><h3><Activity/> Assess claim</h3><small>02</small></div>{flow==="assess"&&kit?<Review kit={kit} tx={assessTx} done={done("Claim assessment")} close={()=>setFlow(null)}/>:<form onSubmit={e=>submit(e,"assess")}><Field label="Claim ID"><input type="number" min="1" value={assessId} onChange={e=>setAssessId(e.target.value)}/></Field><Field label="Expected revision"><input type="number" min="1" value={assessRevision} onChange={e=>setAssessRevision(e.target.value)}/></Field><button>Run consensus review <Activity/></button></form>}</article>
    <article className="card"><div className="card-head"><h3><RefreshCw/> Publish revision</h3><small>03</small></div>{flow==="revise"&&kit?<Review kit={kit} tx={reviseTx} done={done("Claim revision")} close={()=>setFlow(null)}/>:<form onSubmit={e=>submit(e,"revise")}><div className="row"><Field label="Claim ID"><input type="number" min="1" value={reviseId} onChange={e=>setReviseId(e.target.value)}/></Field><Field label="Revision"><input type="number" min="1" value={reviseRevision} onChange={e=>setReviseRevision(e.target.value)}/></Field></div><Field label="Revised statement"><textarea value={revised} onChange={e=>setRevised(e.target.value)} minLength={20} maxLength={500}/></Field><Field label="Context"><input value={revisedContext} onChange={e=>setRevisedContext(e.target.value)}/></Field><button>Review revision <ArrowRight/></button></form>}</article></div>
   </div><aside className="inspector"><div className="inspect-head"><div><span>ON-CHAIN INSPECTOR</span><h3>Claim record</h3></div><button onClick={()=>void record.refetch()}><RefreshCw className={record.isFetching?"spin":""}/></button></div><div className="lookup"><input type="number" min="1" value={lookup} onChange={e=>setLookup(Number(e.target.value))}/><button onClick={()=>void record.refetch()}>Load</button></div>{record.isLoading?<div className="empty">Reading finalized state…</div>:record.isError?<div className="empty">Claim not found or RPC unavailable.</div>:record.data?<><div className="record-top"><div><small>{record.data.claim.nct_id}</small><h4>Claim #{lookup}</h4></div><Pill value={record.data.assessment?.verdict||record.data.claim.status}/></div><blockquote>{record.data.claim.statement}</blockquote><dl><div><dt>Revision</dt><dd>{record.data.claim.revision}</dd></div><div><dt>Assessments</dt><dd>{record.data.claim.assessment_count}</dd></div><div><dt>Owner</dt><dd>{short(record.data.claim.owner)}</dd></div><div><dt>Context</dt><dd>{record.data.claim.context}</dd></div></dl>{record.data.assessment?<div className="assessment"><div className="assessment-title"><Pill value={record.data.assessment.verdict}/><span>{record.data.assessment.reason_code}</span></div><p><b>Cited outcome</b>{record.data.assessment.cited_primary_outcome||"No bounded citation"}</p><p><b>Evidence digest</b><code>{record.data.assessment.evidence_sha256}</code></p>{record.data.assessment.source&&<a href={record.data.assessment.source} target="_blank">Open canonical record <ExternalLink/></a>}</div>:<div className="empty small">No assessment snapshot yet.</div>}</>:<div className="empty">Load a claim to inspect evidence.</div>}</aside></div></section>
   <section id="limits" className="section limits"><div><span>HONEST BOUNDARIES</span><h2>Alignment is not medical truth.</h2></div><div className="limit-grid"><article><CheckCircle2/><h3>What it establishes</h3><p>Whether a statement aligns with the registered primary outcome measures, descriptions and time frames in the fetched NCT record.</p></article><article><X/><h3>What it never claims</h3><p>No efficacy, safety, FDA approval, statistical significance, treatment recommendation or medical advice.</p></article><article><ShieldCheck/><h3>How it fails safely</h3><p>Missing identity, oversized evidence, too many outcomes, invalid citations or source failure produce INCONCLUSIVE, never a positive label.</p></article></div></section>
  </main><footer><div className="brand"><span className="logo"><img src="/trialclaim-logo.png" alt=""/></span><b>TrialClaim</b></div><p>Registered outcomes. Bounded judgment. Durable provenance.</p><a href="https://clinicaltrials.gov/data-api" target="_blank">ClinicalTrials.gov API</a></footer>
 </>
}
function Review({kit,tx,done,close}:{kit:NonNullable<ReturnType<typeof useTransactionKit>>;tx:SubmitInput;done:(s:TrackedStatus)=>void;close:()=>void}){return <div className="review"><button className="close" onClick={close}><X/> Close review</button><GenLayerTransactionPanel kit={kit} tx={tx} network={GENLAYER_NETWORK.chainName} theme="light" trackUntil="finalized" onDone={done}/></div>}
